import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { isSupabaseConfigured, supabase } from './lib/supabase';
import type { Company, JD, Version } from './types';

const now=new Date().toISOString(), uid='demo-user';
const demoCompanies:Company[]=[
  {id:'c1',user_id:uid,name:'TechFlow Inc.',website:'https://techflow.example',industry:'Technology',location:'San Francisco, CA',status:'active',created_at:now,updated_at:now},
  {id:'c2',user_id:uid,name:'Global Finance',website:'https://globalfinance.example',industry:'Financial Services',location:'New York, NY',status:'active',created_at:now,updated_at:now},
  {id:'c3',user_id:uid,name:'MediCore Health',website:'https://medicore.example',industry:'Healthcare',location:'Boston, MA',status:'active',created_at:now,updated_at:now},
];
const base=(p:Partial<JD>):JD=>({id:'j1',user_id:uid,company_id:'c1',job_title:'Senior Frontend Engineer',department:'Engineering',location:'Remote',work_mode:'Remote',job_type:'Full-time',min_experience_years:5,max_experience_years:8,required_skills:['React','TypeScript','Tailwind CSS','Unit Testing'],nice_to_have_skills:['Next.js','GraphQL'],responsibilities:'Build accessible, high-quality product experiences.\nPartner with design and backend teams.\nMentor engineers and improve frontend standards.',qualifications:'5+ years building modern web applications.\nStrong TypeScript and React expertise.',jd_text:'We are looking for a Senior Frontend Engineer to join our product engineering team and help create thoughtful, reliable experiences for hiring teams worldwide.',shortlist_score:88,status:'active',current_version:2,current_jd_hash:'8f8cb80a',created_at:now,updated_at:now,...p});
const demoJds:JD[]=[base({}),base({id:'j2',company_id:'c2',job_title:'Financial Analyst Intern',department:'Finance',work_mode:'Hybrid',min_experience_years:0,max_experience_years:1,required_skills:['Excel','Financial Modeling'],status:'draft',current_version:1,current_jd_hash:'2bd91aa0'}),base({id:'j3',company_id:'c3',job_title:'Marketing Coordinator',department:'Marketing',work_mode:'Onsite',min_experience_years:2,max_experience_years:4,required_skills:['SEO','Content Strategy'],status:'archived',current_version:3,current_jd_hash:'dd814c10'})];

type Store={companies:Company[];jds:JD[];versions:Version[];loading:boolean;refresh:()=>Promise<void>;saveCompany:(v:Partial<Company>)=>Promise<Company>;saveJD:(v:Partial<JD>,note?:string)=>Promise<JD>;cloneJD:(jd:JD)=>Promise<JD>;archiveJD:(jd:JD)=>Promise<void>;restoreVersion:(v:Version)=>Promise<JD>};
const Ctx=createContext<Store|null>(null);
const hash=async(v:unknown)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v))))).map(x=>x.toString(16).padStart(2,'0')).join('');
const ls=<T,>(k:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'') as T}catch{return f}};

export function DataProvider({children}:{children:ReactNode}){
 const [companies,setCompanies]=useState<Company[]>(()=>ls('jdm_companies',demoCompanies)); const [jds,setJds]=useState<JD[]>(()=>ls('jdm_jds',demoJds)); const [versions,setVersions]=useState<Version[]>(()=>ls('jdm_versions',[])); const [loading,setLoading]=useState(false);
 const refresh=async()=>{if(!supabase)return;setLoading(true);const [c,j,v]=await Promise.all([supabase.from('companies').select('*').order('updated_at',{ascending:false}),supabase.from('jd_templates').select('*, companies(name)').order('updated_at',{ascending:false}),supabase.from('jd_versions').select('*').order('version_number',{ascending:false})]);if(c.data)setCompanies(c.data);if(j.data)setJds(j.data as JD[]);if(v.data)setVersions(v.data);setLoading(false)};
 useEffect(()=>{if(isSupabaseConfigured)refresh()},[]); useEffect(()=>{if(!supabase){localStorage.setItem('jdm_companies',JSON.stringify(companies));localStorage.setItem('jdm_jds',JSON.stringify(jds));localStorage.setItem('jdm_versions',JSON.stringify(versions))}},[companies,jds,versions]);
 const saveCompany=async(v:Partial<Company>)=>{const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};const item={...v,id:v.id||crypto.randomUUID(),user_id:user?.id||uid,created_at:v.created_at||now,updated_at:new Date().toISOString()} as Company;if(supabase){const {data,error}=await supabase.from('companies').upsert(item).select().single();if(error)throw error;await refresh();return data}setCompanies(x=>[item,...x.filter(y=>y.id!==item.id)]);return item};
 const saveJD=async(v:Partial<JD>,note='Updated job description')=>{const old=jds.find(x=>x.id===v.id);const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};const version=old?(old.current_version+1):1;const snap={...old,...v,current_version:version,updated_at:new Date().toISOString()};const digest=await hash(snap);const item={...snap,id:v.id||crypto.randomUUID(),user_id:user?.id||uid,current_jd_hash:digest,created_at:v.created_at||now} as JD;const ver:Version={id:crypto.randomUUID(),user_id:item.user_id,jd_template_id:item.id,company_id:item.company_id,version_number:version,jd_snapshot_json:item,jd_hash:digest,change_note:old?note:'Initial version',created_at:new Date().toISOString()};if(supabase){const {companies:_joinedCompany,...dbItem}=item;const {error}=await supabase.from('jd_templates').upsert(dbItem);if(error)throw error;const {error:ve}=await supabase.from('jd_versions').insert(ver);if(ve)throw ve;await refresh()}else{setJds(x=>[item,...x.filter(y=>y.id!==item.id)]);setVersions(x=>[ver,...x])}return item};
 const cloneJD=async(jd:JD)=>saveJD({...jd,id:undefined,job_title:`${jd.job_title} Copy`,current_version:undefined,created_at:undefined},'Cloned JD');
 const archiveJD=async(jd:JD)=>{await saveJD({...jd,status:jd.status==='archived'?'active':'archived'},jd.status==='archived'?'Restored from archive':'Archived')};
 const restoreVersion=async(v:Version)=>saveJD({...v.jd_snapshot_json,id:v.jd_template_id},`Restored from version ${v.version_number}`);
 return <Ctx.Provider value={{companies,jds,versions,loading,refresh,saveCompany,saveJD,cloneJD,archiveJD,restoreVersion}}>{children}</Ctx.Provider>;
}
export const useData=()=>{const c=useContext(Ctx);if(!c)throw Error('Missing DataProvider');return c};
